// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: github.com/johnsiilver/zuul/internal/meta/metapb/meta.proto

// Package zuul.meta is the wire format for Zuul's meta shard: a small replicated
// map from replica id to that node's addresses. It is the cluster's own topology
// record (distinct from dragonboat's Raft membership), letting any node resolve a
// shard leader's client-facing forwarding address — including for nodes added at
// runtime, whose addresses no static config could know.

package metapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Member is one node's entry in the topology.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// replica_id is the node's stable replica id within every shard.
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// raft_address is the dragonboat Raft transport address (host:port).
	RaftAddress string `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	// zuul_grpc_address is the node's client-facing / forwarding gRPC address.
	ZuulGrpcAddress string `protobuf:"bytes,3,opt,name=zuul_grpc_address,json=zuulGrpcAddress,proto3" json:"zuul_grpc_address,omitempty"`
	// node_host_id is the dragonboat NodeHostID (used in gossip addressing).
	NodeHostId    string `protobuf:"bytes,4,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *Member) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *Member) GetZuulGrpcAddress() string {
	if x != nil {
		return x.ZuulGrpcAddress
	}
	return ""
}

func (x *Member) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

// MetaCommand is one meta-shard Raft log entry: exactly one field is set.
type MetaCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*MetaCommand_Put
	//	*MetaCommand_Delete
	Cmd           isMetaCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaCommand) Reset() {
	*x = MetaCommand{}
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaCommand) ProtoMessage() {}

func (x *MetaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaCommand.ProtoReflect.Descriptor instead.
func (*MetaCommand) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescGZIP(), []int{1}
}

func (x *MetaCommand) GetCmd() isMetaCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *MetaCommand) GetPut() *Member {
	if x != nil {
		if x, ok := x.Cmd.(*MetaCommand_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *MetaCommand) GetDelete() uint64 {
	if x != nil {
		if x, ok := x.Cmd.(*MetaCommand_Delete); ok {
			return x.Delete
		}
	}
	return 0
}

type isMetaCommand_Cmd interface {
	isMetaCommand_Cmd()
}

type MetaCommand_Put struct {
	// put adds or updates a member.
	Put *Member `protobuf:"bytes,1,opt,name=put,proto3,oneof"`
}

type MetaCommand_Delete struct {
	// delete removes the member with this replica id.
	Delete uint64 `protobuf:"varint,2,opt,name=delete,proto3,oneof"`
}

func (*MetaCommand_Put) isMetaCommand_Cmd() {}

func (*MetaCommand_Delete) isMetaCommand_Cmd() {}

// MetaResult is returned from applying a MetaCommand.
type MetaResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// revision is the meta-store logical clock after the command was applied.
	Revision      uint64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaResult) Reset() {
	*x = MetaResult{}
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaResult) ProtoMessage() {}

func (x *MetaResult) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaResult.ProtoReflect.Descriptor instead.
func (*MetaResult) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescGZIP(), []int{2}
}

func (x *MetaResult) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// MetaSnapshot is the full meta-store state for SaveSnapshot / RecoverFromSnapshot.
type MetaSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// revision is the meta-store logical clock.
	Revision uint64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// members is every known member, sorted by replica id.
	Members       []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaSnapshot) Reset() {
	*x = MetaSnapshot{}
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaSnapshot) ProtoMessage() {}

func (x *MetaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaSnapshot.ProtoReflect.Descriptor instead.
func (*MetaSnapshot) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescGZIP(), []int{3}
}

func (x *MetaSnapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *MetaSnapshot) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto protoreflect.FileDescriptor

const file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDesc = "" +
	"\n" +
	";github.com/johnsiilver/zuul/internal/meta/metapb/meta.proto\x12\tzuul.meta\"\x98\x01\n" +
	"\x06Member\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\x04R\treplicaId\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\x12*\n" +
	"\x11zuul_grpc_address\x18\x03 \x01(\tR\x0fzuulGrpcAddress\x12 \n" +
	"\fnode_host_id\x18\x04 \x01(\tR\n" +
	"nodeHostId\"U\n" +
	"\vMetaCommand\x12%\n" +
	"\x03put\x18\x01 \x01(\v2\x11.zuul.meta.MemberH\x00R\x03put\x12\x18\n" +
	"\x06delete\x18\x02 \x01(\x04H\x00R\x06deleteB\x05\n" +
	"\x03cmd\"(\n" +
	"\n" +
	"MetaResult\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"W\n" +
	"\fMetaSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12+\n" +
	"\amembers\x18\x02 \x03(\v2\x11.zuul.meta.MemberR\amembersB9Z7github.com/johnsiilver/zuul/internal/meta/metapb;metapbb\x06proto3"

var (
	file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescOnce sync.Once
	file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescData []byte
)

func file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescGZIP() []byte {
	file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescOnce.Do(func() {
		file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDesc), len(file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDesc)))
	})
	return file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDescData
}

var file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_goTypes = []any{
	(*Member)(nil),       // 0: zuul.meta.Member
	(*MetaCommand)(nil),  // 1: zuul.meta.MetaCommand
	(*MetaResult)(nil),   // 2: zuul.meta.MetaResult
	(*MetaSnapshot)(nil), // 3: zuul.meta.MetaSnapshot
}
var file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_depIdxs = []int32{
	0, // 0: zuul.meta.MetaCommand.put:type_name -> zuul.meta.Member
	0, // 1: zuul.meta.MetaSnapshot.members:type_name -> zuul.meta.Member
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_init() }
func file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_init() {
	if File_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto != nil {
		return
	}
	file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes[1].OneofWrappers = []any{
		(*MetaCommand_Put)(nil),
		(*MetaCommand_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDesc), len(file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_goTypes,
		DependencyIndexes: file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_depIdxs,
		MessageInfos:      file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_msgTypes,
	}.Build()
	File_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto = out.File
	file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_goTypes = nil
	file_github_com_johnsiilver_zuul_internal_meta_metapb_meta_proto_depIdxs = nil
}
