// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: github.com/johnsiilver/zuul/internal/raft/fsm/fsmpb/fsm.proto

// Package zuul.fsm is Zuul's internal replicated-state-machine wire format: the
// commands a shard leader proposes into the Raft log, the result the state
// machine returns from applying one, and the full-shard snapshot used for log
// compaction and replica catch-up. It is an implementation detail of the
// consensus core, not a client API, and is marshalled with vtprotobuf on the hot
// path.
//
// Determinism rule: applying a command must be a pure function of the command
// bytes and current state, identical on every replica. Anything time-dependent
// is therefore stamped by the proposing leader into the command (the *_unix_nano
// fields) rather than read from the local clock during apply.

package fsmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome is the deterministic, replicated result classification of applying a
// command. It is identical on every replica.
type Outcome int32

const (
	// OUTCOME_UNKNOWN is the unset zero value and never returned by a valid apply.
	Outcome_OUTCOME_UNKNOWN Outcome = 0
	// OUTCOME_GRANTED: the lock/leadership was granted to the client (fencing_token
	// is set). Also returned for an idempotent re-grant to the current holder.
	Outcome_OUTCOME_GRANTED Outcome = 1
	// OUTCOME_QUEUED: the client was appended to the FIFO queue (queue_position set).
	Outcome_OUTCOME_QUEUED Outcome = 2
	// OUTCOME_NOT_ACQUIRED: a try-lock found the lock held (current_holder set).
	Outcome_OUTCOME_NOT_ACQUIRED Outcome = 3
	// OUTCOME_RELEASED: the lock/leadership was released; a waiter may have been
	// promoted.
	Outcome_OUTCOME_RELEASED Outcome = 4
	// OUTCOME_NOT_HOLDER: the client does not hold the lock/leadership it acted on.
	Outcome_OUTCOME_NOT_HOLDER Outcome = 5
	// OUTCOME_STALE_TOKEN: the presented fencing_token did not match the holder's.
	Outcome_OUTCOME_STALE_TOKEN Outcome = 6
	// OUTCOME_NO_LEASE: the client has no live lease in this shard.
	Outcome_OUTCOME_NO_LEASE Outcome = 7
	// OUTCOME_LEASE_GRANTED: a lease was created or refreshed (lease_deadline set).
	Outcome_OUTCOME_LEASE_GRANTED Outcome = 8
	// OUTCOME_LEASE_RENEWED: an existing lease's deadline was extended.
	Outcome_OUTCOME_LEASE_RENEWED Outcome = 9
	// OUTCOME_LEASE_REVOKED: a lease was revoked and its locks released.
	Outcome_OUTCOME_LEASE_REVOKED Outcome = 10
	// OUTCOME_LEASE_EXPIRED: a due lease was expired and its locks released.
	Outcome_OUTCOME_LEASE_EXPIRED Outcome = 11
	// OUTCOME_VALUE_UPDATED: a leader's published value was updated (Proclaim).
	Outcome_OUTCOME_VALUE_UPDATED Outcome = 12
	// OUTCOME_NOT_FOUND: the target lock/lease did not exist.
	Outcome_OUTCOME_NOT_FOUND Outcome = 13
	// OUTCOME_NOOP: the command was valid but changed nothing (e.g. a CancelWait for
	// a client not queued, or a LeaseExpire no longer past due).
	Outcome_OUTCOME_NOOP Outcome = 14
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0:  "OUTCOME_UNKNOWN",
		1:  "OUTCOME_GRANTED",
		2:  "OUTCOME_QUEUED",
		3:  "OUTCOME_NOT_ACQUIRED",
		4:  "OUTCOME_RELEASED",
		5:  "OUTCOME_NOT_HOLDER",
		6:  "OUTCOME_STALE_TOKEN",
		7:  "OUTCOME_NO_LEASE",
		8:  "OUTCOME_LEASE_GRANTED",
		9:  "OUTCOME_LEASE_RENEWED",
		10: "OUTCOME_LEASE_REVOKED",
		11: "OUTCOME_LEASE_EXPIRED",
		12: "OUTCOME_VALUE_UPDATED",
		13: "OUTCOME_NOT_FOUND",
		14: "OUTCOME_NOOP",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNKNOWN":       0,
		"OUTCOME_GRANTED":       1,
		"OUTCOME_QUEUED":        2,
		"OUTCOME_NOT_ACQUIRED":  3,
		"OUTCOME_RELEASED":      4,
		"OUTCOME_NOT_HOLDER":    5,
		"OUTCOME_STALE_TOKEN":   6,
		"OUTCOME_NO_LEASE":      7,
		"OUTCOME_LEASE_GRANTED": 8,
		"OUTCOME_LEASE_RENEWED": 9,
		"OUTCOME_LEASE_REVOKED": 10,
		"OUTCOME_LEASE_EXPIRED": 11,
		"OUTCOME_VALUE_UPDATED": 12,
		"OUTCOME_NOT_FOUND":     13,
		"OUTCOME_NOOP":          14,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{0}
}

// Command is one Raft log entry: exactly one of the inner commands is set.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Command_AcquireLock
	//	*Command_ReleaseLock
	//	*Command_CancelWait
	//	*Command_LeaseGrant
	//	*Command_LeaseKeepAlive
	//	*Command_LeaseRevoke
	//	*Command_LeaseExpire
	//	*Command_Campaign
	//	*Command_Proclaim
	//	*Command_Resign
	Cmd           isCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCmd() isCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Command) GetAcquireLock() *AcquireLock {
	if x != nil {
		if x, ok := x.Cmd.(*Command_AcquireLock); ok {
			return x.AcquireLock
		}
	}
	return nil
}

func (x *Command) GetReleaseLock() *ReleaseLock {
	if x != nil {
		if x, ok := x.Cmd.(*Command_ReleaseLock); ok {
			return x.ReleaseLock
		}
	}
	return nil
}

func (x *Command) GetCancelWait() *CancelWait {
	if x != nil {
		if x, ok := x.Cmd.(*Command_CancelWait); ok {
			return x.CancelWait
		}
	}
	return nil
}

func (x *Command) GetLeaseGrant() *LeaseGrant {
	if x != nil {
		if x, ok := x.Cmd.(*Command_LeaseGrant); ok {
			return x.LeaseGrant
		}
	}
	return nil
}

func (x *Command) GetLeaseKeepAlive() *LeaseKeepAlive {
	if x != nil {
		if x, ok := x.Cmd.(*Command_LeaseKeepAlive); ok {
			return x.LeaseKeepAlive
		}
	}
	return nil
}

func (x *Command) GetLeaseRevoke() *LeaseRevoke {
	if x != nil {
		if x, ok := x.Cmd.(*Command_LeaseRevoke); ok {
			return x.LeaseRevoke
		}
	}
	return nil
}

func (x *Command) GetLeaseExpire() *LeaseExpire {
	if x != nil {
		if x, ok := x.Cmd.(*Command_LeaseExpire); ok {
			return x.LeaseExpire
		}
	}
	return nil
}

func (x *Command) GetCampaign() *Campaign {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Campaign); ok {
			return x.Campaign
		}
	}
	return nil
}

func (x *Command) GetProclaim() *Proclaim {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Proclaim); ok {
			return x.Proclaim
		}
	}
	return nil
}

func (x *Command) GetResign() *Resign {
	if x != nil {
		if x, ok := x.Cmd.(*Command_Resign); ok {
			return x.Resign
		}
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_AcquireLock struct {
	AcquireLock *AcquireLock `protobuf:"bytes,1,opt,name=acquire_lock,json=acquireLock,proto3,oneof"`
}

type Command_ReleaseLock struct {
	ReleaseLock *ReleaseLock `protobuf:"bytes,2,opt,name=release_lock,json=releaseLock,proto3,oneof"`
}

type Command_CancelWait struct {
	CancelWait *CancelWait `protobuf:"bytes,3,opt,name=cancel_wait,json=cancelWait,proto3,oneof"`
}

type Command_LeaseGrant struct {
	LeaseGrant *LeaseGrant `protobuf:"bytes,4,opt,name=lease_grant,json=leaseGrant,proto3,oneof"`
}

type Command_LeaseKeepAlive struct {
	LeaseKeepAlive *LeaseKeepAlive `protobuf:"bytes,5,opt,name=lease_keep_alive,json=leaseKeepAlive,proto3,oneof"`
}

type Command_LeaseRevoke struct {
	LeaseRevoke *LeaseRevoke `protobuf:"bytes,6,opt,name=lease_revoke,json=leaseRevoke,proto3,oneof"`
}

type Command_LeaseExpire struct {
	LeaseExpire *LeaseExpire `protobuf:"bytes,7,opt,name=lease_expire,json=leaseExpire,proto3,oneof"`
}

type Command_Campaign struct {
	Campaign *Campaign `protobuf:"bytes,8,opt,name=campaign,proto3,oneof"`
}

type Command_Proclaim struct {
	Proclaim *Proclaim `protobuf:"bytes,9,opt,name=proclaim,proto3,oneof"`
}

type Command_Resign struct {
	Resign *Resign `protobuf:"bytes,10,opt,name=resign,proto3,oneof"`
}

func (*Command_AcquireLock) isCommand_Cmd() {}

func (*Command_ReleaseLock) isCommand_Cmd() {}

func (*Command_CancelWait) isCommand_Cmd() {}

func (*Command_LeaseGrant) isCommand_Cmd() {}

func (*Command_LeaseKeepAlive) isCommand_Cmd() {}

func (*Command_LeaseRevoke) isCommand_Cmd() {}

func (*Command_LeaseExpire) isCommand_Cmd() {}

func (*Command_Campaign) isCommand_Cmd() {}

func (*Command_Proclaim) isCommand_Cmd() {}

func (*Command_Resign) isCommand_Cmd() {}

// AcquireLock requests the named lock for a client. If the lock is free it is
// granted with a fresh fencing token; if held and try_lock is false the client
// is appended to the FIFO queue (Outcome QUEUED); if held and try_lock is true
// the command is a no-op acquire (Outcome NOT_ACQUIRED). A re-applied acquire by
// the current holder is an idempotent GRANTED with the existing token.
type AcquireLock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the acquiring client; it must hold a live lease in this shard.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// try_lock, when true, forbids enqueueing: acquire-or-fail, never wait.
	TryLock       bool `protobuf:"varint,3,opt,name=try_lock,json=tryLock,proto3" json:"try_lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLock) Reset() {
	*x = AcquireLock{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLock) ProtoMessage() {}

func (x *AcquireLock) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLock.ProtoReflect.Descriptor instead.
func (*AcquireLock) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireLock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AcquireLock) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AcquireLock) GetTryLock() bool {
	if x != nil {
		return x.TryLock
	}
	return false
}

// ReleaseLock releases a held lock and promotes the head of its FIFO queue (which
// receives a new fencing token). The token must match the holder's current token.
type ReleaseLock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the releasing holder.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// fencing_token is the holder's token; a mismatch yields Outcome STALE_TOKEN.
	FencingToken  uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLock) Reset() {
	*x = ReleaseLock{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLock) ProtoMessage() {}

func (x *ReleaseLock) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLock.ProtoReflect.Descriptor instead.
func (*ReleaseLock) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseLock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReleaseLock) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReleaseLock) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

// CancelWait removes a client from a lock's FIFO queue without acquiring it. The
// server proposes it when a bounded-wait acquire times out, so abandoned waiters
// never block the line. A no-op (Outcome NOOP) if the client is not queued.
type CancelWait struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the waiter to remove.
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWait) Reset() {
	*x = CancelWait{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWait) ProtoMessage() {}

func (x *CancelWait) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWait.ProtoReflect.Descriptor instead.
func (*CancelWait) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{3}
}

func (x *CancelWait) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CancelWait) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// LeaseGrant creates (or, idempotently, refreshes) a client's lease in this shard.
type LeaseGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the lease owner.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// ttl_ms is the lease duration in milliseconds; stored to recompute renewals.
	TtlMs int64 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// now_unix_nano is the leader's apply-time clock anchor; expiry is now + ttl.
	NowUnixNano   int64 `protobuf:"varint,3,opt,name=now_unix_nano,json=nowUnixNano,proto3" json:"now_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrant) Reset() {
	*x = LeaseGrant{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrant) ProtoMessage() {}

func (x *LeaseGrant) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrant.ProtoReflect.Descriptor instead.
func (*LeaseGrant) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{4}
}

func (x *LeaseGrant) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LeaseGrant) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *LeaseGrant) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

// LeaseKeepAlive extends a lease's expiry to now + ttl using the lease's stored
// ttl. A no-op (Outcome NOT_FOUND) if the lease does not exist.
type LeaseKeepAlive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the lease owner.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// now_unix_nano is the leader's apply-time clock anchor.
	NowUnixNano   int64 `protobuf:"varint,2,opt,name=now_unix_nano,json=nowUnixNano,proto3" json:"now_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseKeepAlive) Reset() {
	*x = LeaseKeepAlive{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseKeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseKeepAlive) ProtoMessage() {}

func (x *LeaseKeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseKeepAlive.ProtoReflect.Descriptor instead.
func (*LeaseKeepAlive) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{5}
}

func (x *LeaseKeepAlive) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LeaseKeepAlive) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

// LeaseRevoke removes a lease immediately, releasing every lock the client holds
// and promoting the next waiter on each.
type LeaseRevoke struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the lease owner.
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRevoke) Reset() {
	*x = LeaseRevoke{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRevoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRevoke) ProtoMessage() {}

func (x *LeaseRevoke) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRevoke.ProtoReflect.Descriptor instead.
func (*LeaseRevoke) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{6}
}

func (x *LeaseRevoke) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// LeaseExpire is proposed only by the shard leader's expiry ticker when a lease
// is due. The state machine re-checks the deadline against now_unix_nano and
// only expires if the lease is still past due (a NOOP otherwise), so it is safe
// against a keepalive that committed after the expire was proposed.
type LeaseExpire struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the lease owner to expire.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// now_unix_nano is the leader's apply-time clock anchor for the due check.
	NowUnixNano   int64 `protobuf:"varint,2,opt,name=now_unix_nano,json=nowUnixNano,proto3" json:"now_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseExpire) Reset() {
	*x = LeaseExpire{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseExpire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseExpire) ProtoMessage() {}

func (x *LeaseExpire) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseExpire.ProtoReflect.Descriptor instead.
func (*LeaseExpire) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseExpire) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LeaseExpire) GetNowUnixNano() int64 {
	if x != nil {
		return x.NowUnixNano
	}
	return 0
}

// Campaign enters a named election: a fenced, lease-bound FIFO contest. Free key
// makes the client leader (GRANTED) with a fresh token and the published value;
// otherwise the client is enqueued (QUEUED) and promoted in arrival order.
type Campaign struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the candidate; it must hold a live lease in this shard.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// value is the payload published while this client leads.
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{8}
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Campaign) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Proclaim updates the leader's published value without changing leadership. The
// token must match the current leader's token.
type Proclaim struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the current leader.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// fencing_token is the leadership token; a mismatch yields STALE_TOKEN.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// value is the new payload to publish.
	Value         []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proclaim) Reset() {
	*x = Proclaim{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proclaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proclaim) ProtoMessage() {}

func (x *Proclaim) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proclaim.ProtoReflect.Descriptor instead.
func (*Proclaim) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{9}
}

func (x *Proclaim) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Proclaim) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Proclaim) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *Proclaim) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Resign relinquishes leadership and promotes the next candidate. The token must
// match the current leader's token.
type Resign struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the resigning leader.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// fencing_token is the leadership token; a mismatch yields STALE_TOKEN.
	FencingToken  uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resign) Reset() {
	*x = Resign{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resign) ProtoMessage() {}

func (x *Resign) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resign.ProtoReflect.Descriptor instead.
func (*Resign) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{10}
}

func (x *Resign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resign) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Resign) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

// CommandResult is what applying a Command returns. It is carried back to the
// proposing call so it can answer the client synchronously.
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// outcome classifies what happened.
	Outcome Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=zuul.fsm.Outcome" json:"outcome,omitempty"`
	// revision is the FSM logical clock after this command was applied.
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// fencing_token is the granted/holder token when relevant (GRANTED); else 0.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// lock_key echoes the affected key (lock or election name).
	LockKey string `protobuf:"bytes,4,opt,name=lock_key,json=lockKey,proto3" json:"lock_key,omitempty"`
	// queue_position is the 1-based place in line on QUEUED; 0 otherwise.
	QueuePosition uint32 `protobuf:"varint,5,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	// current_holder is the holder's client_id on NOT_ACQUIRED; empty otherwise.
	CurrentHolder string `protobuf:"bytes,6,opt,name=current_holder,json=currentHolder,proto3" json:"current_holder,omitempty"`
	// lease_deadline_unix_nano is the new lease deadline on lease outcomes; else 0.
	LeaseDeadlineUnixNano int64 `protobuf:"varint,7,opt,name=lease_deadline_unix_nano,json=leaseDeadlineUnixNano,proto3" json:"lease_deadline_unix_nano,omitempty"`
	// value is the leader's published value when relevant (election outcomes).
	Value         []byte `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{11}
}

func (x *CommandResult) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNKNOWN
}

func (x *CommandResult) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CommandResult) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *CommandResult) GetLockKey() string {
	if x != nil {
		return x.LockKey
	}
	return ""
}

func (x *CommandResult) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *CommandResult) GetCurrentHolder() string {
	if x != nil {
		return x.CurrentHolder
	}
	return ""
}

func (x *CommandResult) GetLeaseDeadlineUnixNano() int64 {
	if x != nil {
		return x.LeaseDeadlineUnixNano
	}
	return 0
}

func (x *CommandResult) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Snapshot is the entire state of one shard's FSM, marshalled for SaveSnapshot
// and reloaded by RecoverFromSnapshot. It exists for log compaction and for
// catching up a restarted or lagging replica — never for cross-restart durability
// (the whole store is in memory).
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// seq is the monotonic counter backing fencing tokens and waiter ordering.
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// revision is the FSM logical clock (bumped per applied write).
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// locks is every lock/election with a holder or a non-empty queue.
	Locks []*LockState `protobuf:"bytes,3,rep,name=locks,proto3" json:"locks,omitempty"`
	// leases is every live lease in this shard.
	Leases        []*LeaseState `protobuf:"bytes,4,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{12}
}

func (x *Snapshot) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Snapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetLocks() []*LockState {
	if x != nil {
		return x.Locks
	}
	return nil
}

func (x *Snapshot) GetLeases() []*LeaseState {
	if x != nil {
		return x.Leases
	}
	return nil
}

// LockState is the persisted state of one lock or election key.
type LockState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock/election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// holder is the current owner; unset when the key is free but has waiters.
	Holder *Owner `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	// token is the holder's current fencing token.
	Token uint64 `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
	// value is the leader's published payload for an election; nil for plain locks.
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// queue is the FIFO of waiters, ordered by enqueue_seq.
	Queue         []*Waiter `protobuf:"bytes,5,rep,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockState) Reset() {
	*x = LockState{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockState) ProtoMessage() {}

func (x *LockState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockState.ProtoReflect.Descriptor instead.
func (*LockState) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{13}
}

func (x *LockState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LockState) GetHolder() *Owner {
	if x != nil {
		return x.Holder
	}
	return nil
}

func (x *LockState) GetToken() uint64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *LockState) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LockState) GetQueue() []*Waiter {
	if x != nil {
		return x.Queue
	}
	return nil
}

// Owner identifies the holder of a lock or the leader of an election.
type Owner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the owning client (also its lease key in this shard).
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{14}
}

func (x *Owner) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Waiter is one entry in a lock/election FIFO queue.
type Waiter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the waiting client.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// enqueue_seq is the seq assigned when the client joined the queue; it defines
	// FIFO order and is stable across promotions.
	EnqueueSeq uint64 `protobuf:"varint,2,opt,name=enqueue_seq,json=enqueueSeq,proto3" json:"enqueue_seq,omitempty"`
	// value is the payload to publish if this waiter is an election candidate.
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Waiter) Reset() {
	*x = Waiter{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Waiter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Waiter) ProtoMessage() {}

func (x *Waiter) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Waiter.ProtoReflect.Descriptor instead.
func (*Waiter) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{15}
}

func (x *Waiter) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Waiter) GetEnqueueSeq() uint64 {
	if x != nil {
		return x.EnqueueSeq
	}
	return 0
}

func (x *Waiter) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// LeaseState is one client's lease within this shard.
type LeaseState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the lease owner.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// ttl_ms is the lease duration used to recompute the deadline on keepalive.
	TtlMs int64 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// expire_at_unix_nano is the absolute deadline; the leader expires the lease
	// once its clock passes this.
	ExpireAtUnixNano int64 `protobuf:"varint,3,opt,name=expire_at_unix_nano,json=expireAtUnixNano,proto3" json:"expire_at_unix_nano,omitempty"`
	// held_keys is the set of lock/election keys this client currently holds, so
	// expiry can release them all.
	HeldKeys      []string `protobuf:"bytes,4,rep,name=held_keys,json=heldKeys,proto3" json:"held_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseState) Reset() {
	*x = LeaseState{}
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseState) ProtoMessage() {}

func (x *LeaseState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseState.ProtoReflect.Descriptor instead.
func (*LeaseState) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP(), []int{16}
}

func (x *LeaseState) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LeaseState) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *LeaseState) GetExpireAtUnixNano() int64 {
	if x != nil {
		return x.ExpireAtUnixNano
	}
	return 0
}

func (x *LeaseState) GetHeldKeys() []string {
	if x != nil {
		return x.HeldKeys
	}
	return nil
}

var File_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto protoreflect.FileDescriptor

const file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDesc = "" +
	"\n" +
	"=github.com/johnsiilver/zuul/internal/raft/fsm/fsmpb/fsm.proto\x12\bzuul.fsm\"\xc8\x04\n" +
	"\aCommand\x12:\n" +
	"\facquire_lock\x18\x01 \x01(\v2\x15.zuul.fsm.AcquireLockH\x00R\vacquireLock\x12:\n" +
	"\frelease_lock\x18\x02 \x01(\v2\x15.zuul.fsm.ReleaseLockH\x00R\vreleaseLock\x127\n" +
	"\vcancel_wait\x18\x03 \x01(\v2\x14.zuul.fsm.CancelWaitH\x00R\n" +
	"cancelWait\x127\n" +
	"\vlease_grant\x18\x04 \x01(\v2\x14.zuul.fsm.LeaseGrantH\x00R\n" +
	"leaseGrant\x12D\n" +
	"\x10lease_keep_alive\x18\x05 \x01(\v2\x18.zuul.fsm.LeaseKeepAliveH\x00R\x0eleaseKeepAlive\x12:\n" +
	"\flease_revoke\x18\x06 \x01(\v2\x15.zuul.fsm.LeaseRevokeH\x00R\vleaseRevoke\x12:\n" +
	"\flease_expire\x18\a \x01(\v2\x15.zuul.fsm.LeaseExpireH\x00R\vleaseExpire\x120\n" +
	"\bcampaign\x18\b \x01(\v2\x12.zuul.fsm.CampaignH\x00R\bcampaign\x120\n" +
	"\bproclaim\x18\t \x01(\v2\x12.zuul.fsm.ProclaimH\x00R\bproclaim\x12*\n" +
	"\x06resign\x18\n" +
	" \x01(\v2\x10.zuul.fsm.ResignH\x00R\x06resignB\x05\n" +
	"\x03cmd\"Y\n" +
	"\vAcquireLock\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x19\n" +
	"\btry_lock\x18\x03 \x01(\bR\atryLock\"c\n" +
	"\vReleaseLock\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\"=\n" +
	"\n" +
	"CancelWait\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"d\n" +
	"\n" +
	"LeaseGrant\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\x12\"\n" +
	"\rnow_unix_nano\x18\x03 \x01(\x03R\vnowUnixNano\"Q\n" +
	"\x0eLeaseKeepAlive\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\rnow_unix_nano\x18\x02 \x01(\x03R\vnowUnixNano\"*\n" +
	"\vLeaseRevoke\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"N\n" +
	"\vLeaseExpire\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\"\n" +
	"\rnow_unix_nano\x18\x02 \x01(\x03R\vnowUnixNano\"Q\n" +
	"\bCampaign\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"v\n" +
	"\bProclaim\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"^\n" +
	"\x06Resign\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\"\xb5\x02\n" +
	"\rCommandResult\x12+\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x11.zuul.fsm.OutcomeR\aoutcome\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x19\n" +
	"\block_key\x18\x04 \x01(\tR\alockKey\x12%\n" +
	"\x0equeue_position\x18\x05 \x01(\rR\rqueuePosition\x12%\n" +
	"\x0ecurrent_holder\x18\x06 \x01(\tR\rcurrentHolder\x127\n" +
	"\x18lease_deadline_unix_nano\x18\a \x01(\x03R\x15leaseDeadlineUnixNano\x12\x14\n" +
	"\x05value\x18\b \x01(\fR\x05value\"\x91\x01\n" +
	"\bSnapshot\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12)\n" +
	"\x05locks\x18\x03 \x03(\v2\x13.zuul.fsm.LockStateR\x05locks\x12,\n" +
	"\x06leases\x18\x04 \x03(\v2\x14.zuul.fsm.LeaseStateR\x06leases\"\x9c\x01\n" +
	"\tLockState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x06holder\x18\x02 \x01(\v2\x0f.zuul.fsm.OwnerR\x06holder\x12\x14\n" +
	"\x05token\x18\x03 \x01(\x04R\x05token\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12&\n" +
	"\x05queue\x18\x05 \x03(\v2\x10.zuul.fsm.WaiterR\x05queue\"$\n" +
	"\x05Owner\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\\\n" +
	"\x06Waiter\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\venqueue_seq\x18\x02 \x01(\x04R\n" +
	"enqueueSeq\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x8c\x01\n" +
	"\n" +
	"LeaseState\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\x12-\n" +
	"\x13expire_at_unix_nano\x18\x03 \x01(\x03R\x10expireAtUnixNano\x12\x1b\n" +
	"\theld_keys\x18\x04 \x03(\tR\bheldKeys*\xee\x02\n" +
	"\aOutcome\x12\x13\n" +
	"\x0fOUTCOME_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fOUTCOME_GRANTED\x10\x01\x12\x12\n" +
	"\x0eOUTCOME_QUEUED\x10\x02\x12\x18\n" +
	"\x14OUTCOME_NOT_ACQUIRED\x10\x03\x12\x14\n" +
	"\x10OUTCOME_RELEASED\x10\x04\x12\x16\n" +
	"\x12OUTCOME_NOT_HOLDER\x10\x05\x12\x17\n" +
	"\x13OUTCOME_STALE_TOKEN\x10\x06\x12\x14\n" +
	"\x10OUTCOME_NO_LEASE\x10\a\x12\x19\n" +
	"\x15OUTCOME_LEASE_GRANTED\x10\b\x12\x19\n" +
	"\x15OUTCOME_LEASE_RENEWED\x10\t\x12\x19\n" +
	"\x15OUTCOME_LEASE_REVOKED\x10\n" +
	"\x12\x19\n" +
	"\x15OUTCOME_LEASE_EXPIRED\x10\v\x12\x19\n" +
	"\x15OUTCOME_VALUE_UPDATED\x10\f\x12\x15\n" +
	"\x11OUTCOME_NOT_FOUND\x10\r\x12\x10\n" +
	"\fOUTCOME_NOOP\x10\x0eB;Z9github.com/johnsiilver/zuul/internal/raft/fsm/fsmpb;fsmpbb\x06proto3"

var (
	file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescOnce sync.Once
	file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescData []byte
)

func file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescGZIP() []byte {
	file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescOnce.Do(func() {
		file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDesc), len(file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDesc)))
	})
	return file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDescData
}

var file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_goTypes = []any{
	(Outcome)(0),           // 0: zuul.fsm.Outcome
	(*Command)(nil),        // 1: zuul.fsm.Command
	(*AcquireLock)(nil),    // 2: zuul.fsm.AcquireLock
	(*ReleaseLock)(nil),    // 3: zuul.fsm.ReleaseLock
	(*CancelWait)(nil),     // 4: zuul.fsm.CancelWait
	(*LeaseGrant)(nil),     // 5: zuul.fsm.LeaseGrant
	(*LeaseKeepAlive)(nil), // 6: zuul.fsm.LeaseKeepAlive
	(*LeaseRevoke)(nil),    // 7: zuul.fsm.LeaseRevoke
	(*LeaseExpire)(nil),    // 8: zuul.fsm.LeaseExpire
	(*Campaign)(nil),       // 9: zuul.fsm.Campaign
	(*Proclaim)(nil),       // 10: zuul.fsm.Proclaim
	(*Resign)(nil),         // 11: zuul.fsm.Resign
	(*CommandResult)(nil),  // 12: zuul.fsm.CommandResult
	(*Snapshot)(nil),       // 13: zuul.fsm.Snapshot
	(*LockState)(nil),      // 14: zuul.fsm.LockState
	(*Owner)(nil),          // 15: zuul.fsm.Owner
	(*Waiter)(nil),         // 16: zuul.fsm.Waiter
	(*LeaseState)(nil),     // 17: zuul.fsm.LeaseState
}
var file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_depIdxs = []int32{
	2,  // 0: zuul.fsm.Command.acquire_lock:type_name -> zuul.fsm.AcquireLock
	3,  // 1: zuul.fsm.Command.release_lock:type_name -> zuul.fsm.ReleaseLock
	4,  // 2: zuul.fsm.Command.cancel_wait:type_name -> zuul.fsm.CancelWait
	5,  // 3: zuul.fsm.Command.lease_grant:type_name -> zuul.fsm.LeaseGrant
	6,  // 4: zuul.fsm.Command.lease_keep_alive:type_name -> zuul.fsm.LeaseKeepAlive
	7,  // 5: zuul.fsm.Command.lease_revoke:type_name -> zuul.fsm.LeaseRevoke
	8,  // 6: zuul.fsm.Command.lease_expire:type_name -> zuul.fsm.LeaseExpire
	9,  // 7: zuul.fsm.Command.campaign:type_name -> zuul.fsm.Campaign
	10, // 8: zuul.fsm.Command.proclaim:type_name -> zuul.fsm.Proclaim
	11, // 9: zuul.fsm.Command.resign:type_name -> zuul.fsm.Resign
	0,  // 10: zuul.fsm.CommandResult.outcome:type_name -> zuul.fsm.Outcome
	14, // 11: zuul.fsm.Snapshot.locks:type_name -> zuul.fsm.LockState
	17, // 12: zuul.fsm.Snapshot.leases:type_name -> zuul.fsm.LeaseState
	15, // 13: zuul.fsm.LockState.holder:type_name -> zuul.fsm.Owner
	16, // 14: zuul.fsm.LockState.queue:type_name -> zuul.fsm.Waiter
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_init() }
func file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_init() {
	if File_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto != nil {
		return
	}
	file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_AcquireLock)(nil),
		(*Command_ReleaseLock)(nil),
		(*Command_CancelWait)(nil),
		(*Command_LeaseGrant)(nil),
		(*Command_LeaseKeepAlive)(nil),
		(*Command_LeaseRevoke)(nil),
		(*Command_LeaseExpire)(nil),
		(*Command_Campaign)(nil),
		(*Command_Proclaim)(nil),
		(*Command_Resign)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDesc), len(file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_goTypes,
		DependencyIndexes: file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_depIdxs,
		EnumInfos:         file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_enumTypes,
		MessageInfos:      file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_msgTypes,
	}.Build()
	File_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto = out.File
	file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_goTypes = nil
	file_github_com_johnsiilver_zuul_internal_raft_fsm_fsmpb_fsm_proto_depIdxs = nil
}
