// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: github.com/johnsiilver/zuul/internal/forward/forwardpb/forward.proto

// Package zuul.forward is Zuul's internal node-to-node forwarding API. Raft
// proposals must originate on a shard's leader, so when a client write lands on a
// node that does not lead the target shard, the node forwards the already-encoded
// FSM command to the leader node's Forwarder, which proposes it locally and
// returns the encoded result. This is an internal plane, never exposed to clients.

package forwardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shard_id is the Raft group the command targets.
	ShardId uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// command is a marshalled zuul.fsm.Command.
	Command       []byte `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeRequest) Reset() {
	*x = ProposeRequest{}
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRequest) ProtoMessage() {}

func (x *ProposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRequest.ProtoReflect.Descriptor instead.
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ProposeRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ProposeRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type ProposeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is a marshalled zuul.fsm.CommandResult.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeResponse) Reset() {
	*x = ProposeResponse{}
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeResponse) ProtoMessage() {}

func (x *ProposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeResponse.ProtoReflect.Descriptor instead.
func (*ProposeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescGZIP(), []int{1}
}

func (x *ProposeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type AddReplicaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shard_id is the Raft group to add the replica to.
	ShardId uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// replica_id is the new replica's id.
	ReplicaId uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// raft_address is the new replica's Raft transport address.
	RaftAddress   string `protobuf:"bytes,3,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplicaRequest) Reset() {
	*x = AddReplicaRequest{}
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplicaRequest) ProtoMessage() {}

func (x *AddReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplicaRequest.ProtoReflect.Descriptor instead.
func (*AddReplicaRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescGZIP(), []int{2}
}

func (x *AddReplicaRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AddReplicaRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *AddReplicaRequest) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

type RemoveReplicaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shard_id is the Raft group to remove the replica from.
	ShardId uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// replica_id is the replica to remove.
	ReplicaId     uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReplicaRequest) Reset() {
	*x = RemoveReplicaRequest{}
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReplicaRequest) ProtoMessage() {}

func (x *RemoveReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReplicaRequest.ProtoReflect.Descriptor instead.
func (*RemoveReplicaRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveReplicaRequest) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *RemoveReplicaRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

type MembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipResponse) Reset() {
	*x = MembershipResponse{}
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipResponse) ProtoMessage() {}

func (x *MembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipResponse.ProtoReflect.Descriptor instead.
func (*MembershipResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescGZIP(), []int{4}
}

var File_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto protoreflect.FileDescriptor

const file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDesc = "" +
	"\n" +
	"Dgithub.com/johnsiilver/zuul/internal/forward/forwardpb/forward.proto\x12\fzuul.forward\"E\n" +
	"\x0eProposeRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand\")\n" +
	"\x0fProposeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"p\n" +
	"\x11AddReplicaRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\x12!\n" +
	"\fraft_address\x18\x03 \x01(\tR\vraftAddress\"P\n" +
	"\x14RemoveReplicaRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\"\x14\n" +
	"\x12MembershipResponse2\xfb\x01\n" +
	"\tForwarder\x12F\n" +
	"\aPropose\x12\x1c.zuul.forward.ProposeRequest\x1a\x1d.zuul.forward.ProposeResponse\x12O\n" +
	"\n" +
	"AddReplica\x12\x1f.zuul.forward.AddReplicaRequest\x1a .zuul.forward.MembershipResponse\x12U\n" +
	"\rRemoveReplica\x12\".zuul.forward.RemoveReplicaRequest\x1a .zuul.forward.MembershipResponseBBZ@github.com/johnsiilver/zuul/internal/forward/forwardpb;forwardpbb\x06proto3"

var (
	file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescOnce sync.Once
	file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescData []byte
)

func file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescGZIP() []byte {
	file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescOnce.Do(func() {
		file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDesc), len(file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDesc)))
	})
	return file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDescData
}

var file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_goTypes = []any{
	(*ProposeRequest)(nil),       // 0: zuul.forward.ProposeRequest
	(*ProposeResponse)(nil),      // 1: zuul.forward.ProposeResponse
	(*AddReplicaRequest)(nil),    // 2: zuul.forward.AddReplicaRequest
	(*RemoveReplicaRequest)(nil), // 3: zuul.forward.RemoveReplicaRequest
	(*MembershipResponse)(nil),   // 4: zuul.forward.MembershipResponse
}
var file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_depIdxs = []int32{
	0, // 0: zuul.forward.Forwarder.Propose:input_type -> zuul.forward.ProposeRequest
	2, // 1: zuul.forward.Forwarder.AddReplica:input_type -> zuul.forward.AddReplicaRequest
	3, // 2: zuul.forward.Forwarder.RemoveReplica:input_type -> zuul.forward.RemoveReplicaRequest
	1, // 3: zuul.forward.Forwarder.Propose:output_type -> zuul.forward.ProposeResponse
	4, // 4: zuul.forward.Forwarder.AddReplica:output_type -> zuul.forward.MembershipResponse
	4, // 5: zuul.forward.Forwarder.RemoveReplica:output_type -> zuul.forward.MembershipResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_init() }
func file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_init() {
	if File_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDesc), len(file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_goTypes,
		DependencyIndexes: file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_depIdxs,
		MessageInfos:      file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_msgTypes,
	}.Build()
	File_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto = out.File
	file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_goTypes = nil
	file_github_com_johnsiilver_zuul_internal_forward_forwardpb_forward_proto_depIdxs = nil
}
