// Code generated by "stringer -type=Category -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownCategory-0]
	_ = x[CatRequest-1]
	_ = x[CatNotFound-2]
	_ = x[CatUnauthenticated-3]
	_ = x[CatPermission-4]
	_ = x[CatPrecondition-5]
	_ = x[CatResourceExhausted-6]
	_ = x[CatUnavailable-7]
	_ = x[CatUnimplemented-8]
	_ = x[CatInternal-9]
}

const _Category_name = "UnknownRequestNotFoundUnauthenticatedPermissionPreconditionResourceExhaustedUnavailableUnimplementedInternal"

var _Category_index = [...]uint8{0, 7, 14, 22, 37, 47, 59, 76, 87, 100, 108}

func (i Category) String() string {
	idx := int(i) - 0
	if idx >= len(_Category_index)-1 {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[idx]:_Category_index[idx+1]]
}
