// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownType-0]
	_ = x[TypeBadRequest-1]
	_ = x[TypeInvalidKeyPath-2]
	_ = x[TypeMissingClientID-3]
	_ = x[TypeMissingCredentials-4]
	_ = x[TypeInvalidToken-5]
	_ = x[TypeIdentityMismatch-6]
	_ = x[TypePeerCertRequired-7]
	_ = x[TypePeerCertUntrusted-8]
	_ = x[TypePeerCertNotAllowed-9]
	_ = x[TypeUnauthorizedKey-10]
	_ = x[TypeUnauthorizedCluster-11]
	_ = x[TypeNoLiveLease-12]
	_ = x[TypeStaleFencingToken-13]
	_ = x[TypeNotLockHolder-14]
	_ = x[TypeNotLeader-15]
	_ = x[TypeNoSession-16]
	_ = x[TypeRateLimited-17]
	_ = x[TypeNotFound-18]
	_ = x[TypeNotAcquired-19]
	_ = x[TypeMembershipDisabled-20]
	_ = x[TypeUnexpectedOutcome-21]
	_ = x[TypeBackend-22]
	_ = x[TypeMarshal-23]
	_ = x[TypeConsensus-24]
	_ = x[TypeConfig-25]
	_ = x[TypeDiscovery-26]
}

const _Type_name = "UnknownBadRequestInvalidKeyPathMissingClientIDMissingCredentialsInvalidTokenIdentityMismatchPeerCertRequiredPeerCertUntrustedPeerCertNotAllowedUnauthorizedKeyUnauthorizedClusterNoLiveLeaseStaleFencingTokenNotLockHolderNotLeaderNoSessionRateLimitedNotFoundNotAcquiredMembershipDisabledUnexpectedOutcomeBackendMarshalConsensusConfigDiscovery"

var _Type_index = [...]uint16{0, 7, 17, 31, 46, 64, 76, 92, 108, 125, 143, 158, 177, 188, 205, 218, 227, 236, 247, 255, 266, 284, 301, 308, 315, 324, 330, 339}

func (i Type) String() string {
	idx := int(i) - 0
	if idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
