// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: github.com/johnsiilver/zuul/proto/zuul/v1/zuul.proto

// Package zuul.v1 is Zuul's native, client-facing gRPC API: distributed locks,
// leader election, sessions/leases, and cluster administration.
//
// Two invariants run through the whole API:
//   - Fencing. Every acquisition (Lock, Campaign) returns a monotonically
//     increasing fencing_token. Every mutating follow-up (Unlock, Proclaim,
//     Resign) must present the token it was given; a stale token is rejected.
//     This is the Kleppmann safety property: a paused-then-resumed client cannot
//     act on a lock that has since moved on.
//   - Leasing. A client identity (client_id) owns its locks and candidacies
//     through a lease that must be kept alive (see Session.KeepAlive). When the
//     lease expires, every resource the client held is released and the next
//     FIFO waiter is promoted. No client can hold a resource forever by crashing.

package zuulv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadMode selects the consistency of a read (Status / Leader).
type ReadMode int32

const (
	// READ_MODE_UNKNOWN is the unset zero value; servers treat it as LINEARIZABLE.
	ReadMode_READ_MODE_UNKNOWN ReadMode = 0
	// READ_MODE_LINEARIZABLE confirms the read against the shard leader
	// (ReadIndex): it reflects every write acknowledged before the read began.
	ReadMode_READ_MODE_LINEARIZABLE ReadMode = 1
	// READ_MODE_STALE serves from the local replica without leader confirmation:
	// faster, but may be slightly behind.
	ReadMode_READ_MODE_STALE ReadMode = 2
)

// Enum value maps for ReadMode.
var (
	ReadMode_name = map[int32]string{
		0: "READ_MODE_UNKNOWN",
		1: "READ_MODE_LINEARIZABLE",
		2: "READ_MODE_STALE",
	}
	ReadMode_value = map[string]int32{
		"READ_MODE_UNKNOWN":      0,
		"READ_MODE_LINEARIZABLE": 1,
		"READ_MODE_STALE":        2,
	}
)

func (x ReadMode) Enum() *ReadMode {
	p := new(ReadMode)
	*p = x
	return p
}

func (x ReadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_enumTypes[0].Descriptor()
}

func (ReadMode) Type() protoreflect.EnumType {
	return &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_enumTypes[0]
}

func (x ReadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadMode.Descriptor instead.
func (ReadMode) EnumDescriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{0}
}

// RecordKind classifies a browsed record. It is best-effort: lock vs election is
// inferred from whether a value has been published.
type RecordKind int32

const (
	// RECORD_KIND_UNKNOWN is the unset zero value.
	RecordKind_RECORD_KIND_UNKNOWN RecordKind = 0
	// RECORD_KIND_LOCK is a plain mutual-exclusion lock.
	RecordKind_RECORD_KIND_LOCK RecordKind = 1
	// RECORD_KIND_ELECTION is a leader election (a value has been published).
	RecordKind_RECORD_KIND_ELECTION RecordKind = 2
)

// Enum value maps for RecordKind.
var (
	RecordKind_name = map[int32]string{
		0: "RECORD_KIND_UNKNOWN",
		1: "RECORD_KIND_LOCK",
		2: "RECORD_KIND_ELECTION",
	}
	RecordKind_value = map[string]int32{
		"RECORD_KIND_UNKNOWN":  0,
		"RECORD_KIND_LOCK":     1,
		"RECORD_KIND_ELECTION": 2,
	}
)

func (x RecordKind) Enum() *RecordKind {
	p := new(RecordKind)
	*p = x
	return p
}

func (x RecordKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordKind) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_enumTypes[1].Descriptor()
}

func (RecordKind) Type() protoreflect.EnumType {
	return &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_enumTypes[1]
}

func (x RecordKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecordKind.Descriptor instead.
func (RecordKind) EnumDescriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{1}
}

type KeepAliveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id identifies the session owner. Set on the first request to claim an
	// identity, or leave empty to be assigned one; ignored on later requests.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// ttl_ms is the requested lease duration in milliseconds. Honored on the first
	// request; the server may clamp it to its configured bounds.
	TtlMs         int64 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveRequest) Reset() {
	*x = KeepAliveRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveRequest) ProtoMessage() {}

func (x *KeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveRequest.ProtoReflect.Descriptor instead.
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{0}
}

func (x *KeepAliveRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *KeepAliveRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type KeepAliveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the session's identity (echoed, or assigned by the server).
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// ttl_ms is the lease duration the server granted (possibly clamped).
	TtlMs int64 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	// deadline_unix_nano is the absolute time, in Unix nanoseconds on the server
	// clock, by which the next heartbeat must arrive to keep the lease alive.
	DeadlineUnixNano int64 `protobuf:"varint,3,opt,name=deadline_unix_nano,json=deadlineUnixNano,proto3" json:"deadline_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeepAliveResponse) Reset() {
	*x = KeepAliveResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveResponse) ProtoMessage() {}

func (x *KeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveResponse.ProtoReflect.Descriptor instead.
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{1}
}

func (x *KeepAliveResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *KeepAliveResponse) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *KeepAliveResponse) GetDeadlineUnixNano() int64 {
	if x != nil {
		return x.DeadlineUnixNano
	}
	return 0
}

type LockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the acquiring session's identity. It must have a live lease.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// wait_deadline_unix_nano bounds a blocking acquire: if the lock is not granted
	// by this absolute server-clock time (Unix nanoseconds), the call returns with
	// acquired = false. 0 means block until acquired or the RPC context ends.
	WaitDeadlineUnixNano int64 `protobuf:"varint,3,opt,name=wait_deadline_unix_nano,json=waitDeadlineUnixNano,proto3" json:"wait_deadline_unix_nano,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{2}
}

func (x *LockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LockRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LockRequest) GetWaitDeadlineUnixNano() int64 {
	if x != nil {
		return x.WaitDeadlineUnixNano
	}
	return 0
}

type LockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acquired reports whether the lock is now held by the caller. It is false only
	// when a bounded wait expired before the lock became available.
	Acquired bool `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	// lock_key is the canonical key of the acquired lock (echoes name).
	LockKey string `protobuf:"bytes,2,opt,name=lock_key,json=lockKey,proto3" json:"lock_key,omitempty"`
	// fencing_token is the monotonic token proving this acquisition. Present it to
	// Unlock. It strictly increases each time the lock changes hands.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// revision is the FSM logical clock at the moment of acquisition.
	Revision      uint64 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{3}
}

func (x *LockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *LockResponse) GetLockKey() string {
	if x != nil {
		return x.LockKey
	}
	return ""
}

func (x *LockResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LockResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type TryLockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the acquiring session's identity. It must have a live lease.
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryLockRequest) Reset() {
	*x = TryLockRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockRequest) ProtoMessage() {}

func (x *TryLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockRequest.ProtoReflect.Descriptor instead.
func (*TryLockRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{4}
}

func (x *TryLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TryLockRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type TryLockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// acquired reports whether the lock was free and is now held by the caller.
	Acquired bool `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	// lock_key is the canonical key of the lock (echoes name).
	LockKey string `protobuf:"bytes,2,opt,name=lock_key,json=lockKey,proto3" json:"lock_key,omitempty"`
	// fencing_token is set only when acquired is true (see LockResponse).
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// revision is the FSM logical clock at the moment of the attempt.
	Revision uint64 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	// current_holder is the client_id currently holding the lock when acquired is
	// false; empty otherwise.
	CurrentHolder string `protobuf:"bytes,5,opt,name=current_holder,json=currentHolder,proto3" json:"current_holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryLockResponse) Reset() {
	*x = TryLockResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockResponse) ProtoMessage() {}

func (x *TryLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockResponse.ProtoReflect.Descriptor instead.
func (*TryLockResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{5}
}

func (x *TryLockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *TryLockResponse) GetLockKey() string {
	if x != nil {
		return x.LockKey
	}
	return ""
}

func (x *TryLockResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *TryLockResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *TryLockResponse) GetCurrentHolder() string {
	if x != nil {
		return x.CurrentHolder
	}
	return ""
}

type UnlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lock_key is the key returned by the acquisition.
	LockKey string `protobuf:"bytes,1,opt,name=lock_key,json=lockKey,proto3" json:"lock_key,omitempty"`
	// client_id is the holder's identity.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// fencing_token is the token from the acquisition. A mismatch is rejected.
	FencingToken  uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{6}
}

func (x *UnlockRequest) GetLockKey() string {
	if x != nil {
		return x.LockKey
	}
	return ""
}

func (x *UnlockRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UnlockRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type UnlockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// revision is the FSM logical clock after the release is applied.
	Revision      uint64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{7}
}

func (x *UnlockResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// read_mode selects linearizable (default) or stale read consistency.
	ReadMode      ReadMode `protobuf:"varint,2,opt,name=read_mode,json=readMode,proto3,enum=zuul.v1.ReadMode" json:"read_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{8}
}

func (x *StatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusRequest) GetReadMode() ReadMode {
	if x != nil {
		return x.ReadMode
	}
	return ReadMode_READ_MODE_UNKNOWN
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// held reports whether the lock currently has a holder.
	Held bool `protobuf:"varint,1,opt,name=held,proto3" json:"held,omitempty"`
	// holder_client_id is the current holder's identity; empty when not held.
	HolderClientId string `protobuf:"bytes,2,opt,name=holder_client_id,json=holderClientId,proto3" json:"holder_client_id,omitempty"`
	// fencing_token is the holder's current token; 0 when not held.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// queue_depth is the number of clients waiting behind the holder.
	QueueDepth uint32 `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	// revision is the FSM logical clock at which this status was read.
	Revision      uint64 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetHeld() bool {
	if x != nil {
		return x.Held
	}
	return false
}

func (x *StatusResponse) GetHolderClientId() string {
	if x != nil {
		return x.HolderClientId
	}
	return ""
}

func (x *StatusResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *StatusResponse) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *StatusResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CampaignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the candidate's identity. It must have a live lease.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// value is the payload published while this candidate leads (e.g. an address).
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// wait_deadline_unix_nano bounds the wait for leadership; 0 means block until
	// elected or the RPC context ends.
	WaitDeadlineUnixNano int64 `protobuf:"varint,4,opt,name=wait_deadline_unix_nano,json=waitDeadlineUnixNano,proto3" json:"wait_deadline_unix_nano,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CampaignRequest) Reset() {
	*x = CampaignRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignRequest) ProtoMessage() {}

func (x *CampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignRequest.ProtoReflect.Descriptor instead.
func (*CampaignRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{10}
}

func (x *CampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CampaignRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CampaignRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CampaignRequest) GetWaitDeadlineUnixNano() int64 {
	if x != nil {
		return x.WaitDeadlineUnixNano
	}
	return 0
}

type CampaignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// leadership reports whether the caller is now the leader. It is false only
	// when a bounded wait expired first.
	Leadership bool `protobuf:"varint,1,opt,name=leadership,proto3" json:"leadership,omitempty"`
	// leader_key is the canonical key of this leadership term (echoes name).
	LeaderKey string `protobuf:"bytes,2,opt,name=leader_key,json=leaderKey,proto3" json:"leader_key,omitempty"`
	// fencing_token proves this leadership term; present it to Proclaim and Resign.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// revision is the FSM logical clock at the moment leadership was won.
	Revision      uint64 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignResponse) Reset() {
	*x = CampaignResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignResponse) ProtoMessage() {}

func (x *CampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignResponse.ProtoReflect.Descriptor instead.
func (*CampaignResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{11}
}

func (x *CampaignResponse) GetLeadership() bool {
	if x != nil {
		return x.Leadership
	}
	return false
}

func (x *CampaignResponse) GetLeaderKey() string {
	if x != nil {
		return x.LeaderKey
	}
	return ""
}

func (x *CampaignResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *CampaignResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ProclaimRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the leader's identity.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// fencing_token is the leadership token. A mismatch is rejected.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// value is the new payload to publish.
	Value         []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProclaimRequest) Reset() {
	*x = ProclaimRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProclaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProclaimRequest) ProtoMessage() {}

func (x *ProclaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProclaimRequest.ProtoReflect.Descriptor instead.
func (*ProclaimRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{12}
}

func (x *ProclaimRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProclaimRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProclaimRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *ProclaimRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProclaimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// revision is the FSM logical clock after the new value is applied.
	Revision      uint64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProclaimResponse) Reset() {
	*x = ProclaimResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProclaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProclaimResponse) ProtoMessage() {}

func (x *ProclaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProclaimResponse.ProtoReflect.Descriptor instead.
func (*ProclaimResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{13}
}

func (x *ProclaimResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type LeaderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// read_mode selects linearizable (default) or stale read consistency.
	ReadMode      ReadMode `protobuf:"varint,2,opt,name=read_mode,json=readMode,proto3,enum=zuul.v1.ReadMode" json:"read_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderRequest) Reset() {
	*x = LeaderRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderRequest) ProtoMessage() {}

func (x *LeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderRequest.ProtoReflect.Descriptor instead.
func (*LeaderRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{14}
}

func (x *LeaderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderRequest) GetReadMode() ReadMode {
	if x != nil {
		return x.ReadMode
	}
	return ReadMode_READ_MODE_UNKNOWN
}

type LeaderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// has_leader reports whether the election currently has a leader.
	HasLeader bool `protobuf:"varint,1,opt,name=has_leader,json=hasLeader,proto3" json:"has_leader,omitempty"`
	// leader_client_id is the current leader's identity; empty when leaderless.
	LeaderClientId string `protobuf:"bytes,2,opt,name=leader_client_id,json=leaderClientId,proto3" json:"leader_client_id,omitempty"`
	// fencing_token is the current leadership token; 0 when leaderless.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// value is the leader's published payload.
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// revision is the FSM logical clock at which this was read.
	Revision      uint64 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderResponse) Reset() {
	*x = LeaderResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderResponse) ProtoMessage() {}

func (x *LeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderResponse.ProtoReflect.Descriptor instead.
func (*LeaderResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{15}
}

func (x *LeaderResponse) GetHasLeader() bool {
	if x != nil {
		return x.HasLeader
	}
	return false
}

func (x *LeaderResponse) GetLeaderClientId() string {
	if x != nil {
		return x.LeaderClientId
	}
	return ""
}

func (x *LeaderResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaderResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LeaderResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ObserveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{16}
}

func (x *ObserveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LeaderEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// has_leader reports whether the election has a leader as of this event.
	HasLeader bool `protobuf:"varint,1,opt,name=has_leader,json=hasLeader,proto3" json:"has_leader,omitempty"`
	// leader_client_id is the leader's identity as of this event; empty when
	// leaderless.
	LeaderClientId string `protobuf:"bytes,2,opt,name=leader_client_id,json=leaderClientId,proto3" json:"leader_client_id,omitempty"`
	// fencing_token is the leadership token as of this event; 0 when leaderless.
	FencingToken uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// value is the leader's published payload as of this event.
	Value []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// revision is the FSM logical clock at which this event was emitted.
	Revision      uint64 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderEvent) Reset() {
	*x = LeaderEvent{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderEvent) ProtoMessage() {}

func (x *LeaderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderEvent.ProtoReflect.Descriptor instead.
func (*LeaderEvent) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{17}
}

func (x *LeaderEvent) GetHasLeader() bool {
	if x != nil {
		return x.HasLeader
	}
	return false
}

func (x *LeaderEvent) GetLeaderClientId() string {
	if x != nil {
		return x.LeaderClientId
	}
	return ""
}

func (x *LeaderEvent) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaderEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LeaderEvent) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ResignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the election key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// client_id is the leader's identity.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// fencing_token is the leadership token. A mismatch is rejected.
	FencingToken  uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResignRequest) Reset() {
	*x = ResignRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResignRequest) ProtoMessage() {}

func (x *ResignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResignRequest.ProtoReflect.Descriptor instead.
func (*ResignRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{18}
}

func (x *ResignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResignRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ResignRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type ResignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// revision is the FSM logical clock after leadership is relinquished.
	Revision      uint64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResignResponse) Reset() {
	*x = ResignResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResignResponse) ProtoMessage() {}

func (x *ResignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResignResponse.ProtoReflect.Descriptor instead.
func (*ResignResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{19}
}

func (x *ResignResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// Endpoint is the network location a leader (master) publishes as its Election
// value so observers can dial it by election path. It is not referenced by any
// RPC: it is a data type marshaled into the free-form Election value bytes
// (Campaign/Proclaim value; Leader/LeaderEvent value). Zuul does not interpret it.
type Endpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host is the master's reachable address: a DNS hostname or an IP literal (IPv4
	// or IPv6). Resolvers dial it as host:port, so "dns:port" endpoints work too.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// port is the TCP port to dial on host.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// metadata is an optional caller-defined payload (any proto message) the master
	// attaches to its address. Carried verbatim; Zuul does not interpret it.
	Metadata      *anypb.Any `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{20}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetMetadata() *anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Member describes one node in the cluster. Both addresses are carried because
// Zuul runs two network planes: dragonboat's Raft transport and Zuul's own
// client-facing gRPC. Forwarding a write to a shard's leader targets that node's
// zuul_grpc_address.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// replica_id is the node's stable replica id within every shard.
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// node_host_id is dragonboat's NodeHostID (used in gossip addressing mode).
	NodeHostId string `protobuf:"bytes,2,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	// raft_address is the dragonboat Raft transport address (host:port).
	RaftAddress string `protobuf:"bytes,3,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	// zuul_grpc_address is the node's client-facing Zuul gRPC address (host:port).
	ZuulGrpcAddress string `protobuf:"bytes,4,opt,name=zuul_grpc_address,json=zuulGrpcAddress,proto3" json:"zuul_grpc_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{21}
}

func (x *Member) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *Member) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

func (x *Member) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *Member) GetZuulGrpcAddress() string {
	if x != nil {
		return x.ZuulGrpcAddress
	}
	return ""
}

type MembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersRequest) Reset() {
	*x = MembersRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersRequest) ProtoMessage() {}

func (x *MembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersRequest.ProtoReflect.Descriptor instead.
func (*MembersRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{22}
}

type MembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// members is the current cluster membership.
	Members       []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersResponse) Reset() {
	*x = MembersResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersResponse) ProtoMessage() {}

func (x *MembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersResponse.ProtoReflect.Descriptor instead.
func (*MembersResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{23}
}

func (x *MembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type AddNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// replica_id is the stable replica id to assign the joining node.
	ReplicaId uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	// node_host_id is the joining node's dragonboat NodeHostID.
	NodeHostId string `protobuf:"bytes,2,opt,name=node_host_id,json=nodeHostId,proto3" json:"node_host_id,omitempty"`
	// raft_address is the joining node's Raft transport address.
	RaftAddress string `protobuf:"bytes,3,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	// zuul_grpc_address is the joining node's client-facing gRPC address.
	ZuulGrpcAddress string `protobuf:"bytes,4,opt,name=zuul_grpc_address,json=zuulGrpcAddress,proto3" json:"zuul_grpc_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{24}
}

func (x *AddNodeRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *AddNodeRequest) GetNodeHostId() string {
	if x != nil {
		return x.NodeHostId
	}
	return ""
}

func (x *AddNodeRequest) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *AddNodeRequest) GetZuulGrpcAddress() string {
	if x != nil {
		return x.ZuulGrpcAddress
	}
	return ""
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{25}
}

type RemoveNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// replica_id is the replica id of the node to remove.
	ReplicaId     uint64 `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveNodeRequest) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{27}
}

type ShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardsRequest) Reset() {
	*x = ShardsRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardsRequest) ProtoMessage() {}

func (x *ShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardsRequest.ProtoReflect.Descriptor instead.
func (*ShardsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{28}
}

type ShardsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shards is the per-shard leadership map as seen by this node.
	Shards        []*ShardInfo `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardsResponse) Reset() {
	*x = ShardsResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardsResponse) ProtoMessage() {}

func (x *ShardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardsResponse.ProtoReflect.Descriptor instead.
func (*ShardsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{29}
}

func (x *ShardsResponse) GetShards() []*ShardInfo {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ShardInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shard_id is the Raft group id.
	ShardId uint64 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// leader_replica_id is the replica id leading this shard; 0 if unknown.
	LeaderReplicaId uint64 `protobuf:"varint,2,opt,name=leader_replica_id,json=leaderReplicaId,proto3" json:"leader_replica_id,omitempty"`
	// term is the Raft term of the current leadership.
	Term uint64 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	// replica_ids lists every replica id participating in this shard.
	ReplicaIds    []uint64 `protobuf:"varint,4,rep,packed,name=replica_ids,json=replicaIds,proto3" json:"replica_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardInfo) Reset() {
	*x = ShardInfo{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardInfo) ProtoMessage() {}

func (x *ShardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardInfo.ProtoReflect.Descriptor instead.
func (*ShardInfo) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{30}
}

func (x *ShardInfo) GetShardId() uint64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardInfo) GetLeaderReplicaId() uint64 {
	if x != nil {
		return x.LeaderReplicaId
	}
	return 0
}

func (x *ShardInfo) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ShardInfo) GetReplicaIds() []uint64 {
	if x != nil {
		return x.ReplicaIds
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{31}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy is this node's self-assessment.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// shard_count is the number of shards this node participates in.
	ShardCount uint64 `protobuf:"varint,2,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	// leader_count is the number of those shards this node currently leads.
	LeaderCount   uint64 `protobuf:"varint,3,opt,name=leader_count,json=leaderCount,proto3" json:"leader_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{32}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetShardCount() uint64 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

func (x *HealthResponse) GetLeaderCount() uint64 {
	if x != nil {
		return x.LeaderCount
	}
	return 0
}

// Record is the summary of one held lock/election.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the lock/election key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// kind is the inferred record kind (best-effort; see RecordKind).
	Kind RecordKind `protobuf:"varint,2,opt,name=kind,proto3,enum=zuul.v1.RecordKind" json:"kind,omitempty"`
	// held reports whether the key currently has a holder/leader.
	Held bool `protobuf:"varint,3,opt,name=held,proto3" json:"held,omitempty"`
	// holder_client_id is the holder/leader's client id.
	HolderClientId string `protobuf:"bytes,4,opt,name=holder_client_id,json=holderClientId,proto3" json:"holder_client_id,omitempty"`
	// fencing_token is the holder's fencing token.
	FencingToken uint64 `protobuf:"varint,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// queue_depth is the number of contenders behind the holder.
	QueueDepth uint32 `protobuf:"varint,6,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	// revision is the FSM logical clock at which this was read.
	Revision      uint64 `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{33}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetKind() RecordKind {
	if x != nil {
		return x.Kind
	}
	return RecordKind_RECORD_KIND_UNKNOWN
}

func (x *Record) GetHeld() bool {
	if x != nil {
		return x.Held
	}
	return false
}

func (x *Record) GetHolderClientId() string {
	if x != nil {
		return x.HolderClientId
	}
	return ""
}

func (x *Record) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *Record) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *Record) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ListRecordsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prefix narrows the result to keys under it (path boundary); empty returns all.
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// limit, when > 0, caps the number of records returned (reserved for pagination;
	// not yet enforced).
	Limit         uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{34}
}

func (x *ListRecordsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListRecordsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRecordsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// records are the matching held locks/elections, sorted by key.
	Records []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// namespaces are the distinct owner segments present under prefix, sorted.
	Namespaces    []string `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{35}
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsResponse) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// Contender is one entry of a key's FIFO wait queue (a client blocked acquiring the
// lock or campaigning).
type Contender struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id is the waiting client.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// position is the 1-based position in the queue.
	Position uint32 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	// enqueue_seq is the waiter's monotonic enqueue order.
	EnqueueSeq    uint64 `protobuf:"varint,3,opt,name=enqueue_seq,json=enqueueSeq,proto3" json:"enqueue_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contender) Reset() {
	*x = Contender{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contender) ProtoMessage() {}

func (x *Contender) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contender.ProtoReflect.Descriptor instead.
func (*Contender) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{36}
}

func (x *Contender) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Contender) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Contender) GetEnqueueSeq() uint64 {
	if x != nil {
		return x.EnqueueSeq
	}
	return 0
}

// Observer is one client watching a key via an Election Observe stream, attributed to
// the node hosting the subscription. Observers are approximate (currently-connected
// streams), not a linearizable count.
type Observer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identity is the observer's authenticated identity; "" if unauthenticated.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// replica_id is the node hosting the subscription.
	ReplicaId     uint64 `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observer) Reset() {
	*x = Observer{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observer) ProtoMessage() {}

func (x *Observer) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observer.ProtoReflect.Descriptor instead.
func (*Observer) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{37}
}

func (x *Observer) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Observer) GetReplicaId() uint64 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

type GetRecordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the lock/election key to inspect.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{38}
}

func (x *GetRecordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRecordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// record is the summary of the key.
	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// value is the published election value; empty for a plain lock.
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// contenders are the FIFO wait-queue entries (replicated, from the FSM).
	Contenders []*Contender `protobuf:"bytes,3,rep,name=contenders,proto3" json:"contenders,omitempty"`
	// observers are the Observe-stream watchers, aggregated cluster-wide.
	Observers []*Observer `protobuf:"bytes,4,rep,name=observers,proto3" json:"observers,omitempty"`
	// partial is true when some node could not be reached for observers, so the
	// observer list may be incomplete.
	Partial       bool `protobuf:"varint,5,opt,name=partial,proto3" json:"partial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP(), []int{39}
}

func (x *GetRecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetRecordResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetRecordResponse) GetContenders() []*Contender {
	if x != nil {
		return x.Contenders
	}
	return nil
}

func (x *GetRecordResponse) GetObservers() []*Observer {
	if x != nil {
		return x.Observers
	}
	return nil
}

func (x *GetRecordResponse) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

var File_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto protoreflect.FileDescriptor

const file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDesc = "" +
	"\n" +
	"4github.com/johnsiilver/zuul/proto/zuul/v1/zuul.proto\x12\azuul.v1\x1a\x19google/protobuf/any.proto\"F\n" +
	"\x10KeepAliveRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\"u\n" +
	"\x11KeepAliveResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\x12,\n" +
	"\x12deadline_unix_nano\x18\x03 \x01(\x03R\x10deadlineUnixNano\"u\n" +
	"\vLockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x125\n" +
	"\x17wait_deadline_unix_nano\x18\x03 \x01(\x03R\x14waitDeadlineUnixNano\"\x86\x01\n" +
	"\fLockResponse\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x19\n" +
	"\block_key\x18\x02 \x01(\tR\alockKey\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\"A\n" +
	"\x0eTryLockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\xb0\x01\n" +
	"\x0fTryLockResponse\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x19\n" +
	"\block_key\x18\x02 \x01(\tR\alockKey\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12%\n" +
	"\x0ecurrent_holder\x18\x05 \x01(\tR\rcurrentHolder\"l\n" +
	"\rUnlockRequest\x12\x19\n" +
	"\block_key\x18\x01 \x01(\tR\alockKey\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\",\n" +
	"\x0eUnlockResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"S\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\tread_mode\x18\x02 \x01(\x0e2\x11.zuul.v1.ReadModeR\breadMode\"\xb0\x01\n" +
	"\x0eStatusResponse\x12\x12\n" +
	"\x04held\x18\x01 \x01(\bR\x04held\x12(\n" +
	"\x10holder_client_id\x18\x02 \x01(\tR\x0eholderClientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\rR\n" +
	"queueDepth\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\"\x8f\x01\n" +
	"\x0fCampaignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x125\n" +
	"\x17wait_deadline_unix_nano\x18\x04 \x01(\x03R\x14waitDeadlineUnixNano\"\x92\x01\n" +
	"\x10CampaignResponse\x12\x1e\n" +
	"\n" +
	"leadership\x18\x01 \x01(\bR\n" +
	"leadership\x12\x1d\n" +
	"\n" +
	"leader_key\x18\x02 \x01(\tR\tleaderKey\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\"}\n" +
	"\x0fProclaimRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\".\n" +
	"\x10ProclaimResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"S\n" +
	"\rLeaderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\tread_mode\x18\x02 \x01(\x0e2\x11.zuul.v1.ReadModeR\breadMode\"\xb0\x01\n" +
	"\x0eLeaderResponse\x12\x1d\n" +
	"\n" +
	"has_leader\x18\x01 \x01(\bR\thasLeader\x12(\n" +
	"\x10leader_client_id\x18\x02 \x01(\tR\x0eleaderClientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\"$\n" +
	"\x0eObserveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xad\x01\n" +
	"\vLeaderEvent\x12\x1d\n" +
	"\n" +
	"has_leader\x18\x01 \x01(\bR\thasLeader\x12(\n" +
	"\x10leader_client_id\x18\x02 \x01(\tR\x0eleaderClientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\"e\n" +
	"\rResignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\",\n" +
	"\x0eResignResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"d\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\bmetadata\"\x98\x01\n" +
	"\x06Member\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\x04R\treplicaId\x12 \n" +
	"\fnode_host_id\x18\x02 \x01(\tR\n" +
	"nodeHostId\x12!\n" +
	"\fraft_address\x18\x03 \x01(\tR\vraftAddress\x12*\n" +
	"\x11zuul_grpc_address\x18\x04 \x01(\tR\x0fzuulGrpcAddress\"\x10\n" +
	"\x0eMembersRequest\"<\n" +
	"\x0fMembersResponse\x12)\n" +
	"\amembers\x18\x01 \x03(\v2\x0f.zuul.v1.MemberR\amembers\"\xa0\x01\n" +
	"\x0eAddNodeRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\x04R\treplicaId\x12 \n" +
	"\fnode_host_id\x18\x02 \x01(\tR\n" +
	"nodeHostId\x12!\n" +
	"\fraft_address\x18\x03 \x01(\tR\vraftAddress\x12*\n" +
	"\x11zuul_grpc_address\x18\x04 \x01(\tR\x0fzuulGrpcAddress\"\x11\n" +
	"\x0fAddNodeResponse\"2\n" +
	"\x11RemoveNodeRequest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\x04R\treplicaId\"\x14\n" +
	"\x12RemoveNodeResponse\"\x0f\n" +
	"\rShardsRequest\"<\n" +
	"\x0eShardsResponse\x12*\n" +
	"\x06shards\x18\x01 \x03(\v2\x12.zuul.v1.ShardInfoR\x06shards\"\x87\x01\n" +
	"\tShardInfo\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x04R\ashardId\x12*\n" +
	"\x11leader_replica_id\x18\x02 \x01(\x04R\x0fleaderReplicaId\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1f\n" +
	"\vreplica_ids\x18\x04 \x03(\x04R\n" +
	"replicaIds\"\x0f\n" +
	"\rHealthRequest\"n\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vshard_count\x18\x02 \x01(\x04R\n" +
	"shardCount\x12!\n" +
	"\fleader_count\x18\x03 \x01(\x04R\vleaderCount\"\xe3\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.zuul.v1.RecordKindR\x04kind\x12\x12\n" +
	"\x04held\x18\x03 \x01(\bR\x04held\x12(\n" +
	"\x10holder_client_id\x18\x04 \x01(\tR\x0eholderClientId\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\x04R\ffencingToken\x12\x1f\n" +
	"\vqueue_depth\x18\x06 \x01(\rR\n" +
	"queueDepth\x12\x1a\n" +
	"\brevision\x18\a \x01(\x04R\brevision\"B\n" +
	"\x12ListRecordsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"`\n" +
	"\x13ListRecordsResponse\x12)\n" +
	"\arecords\x18\x01 \x03(\v2\x0f.zuul.v1.RecordR\arecords\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\tR\n" +
	"namespaces\"e\n" +
	"\tContender\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\rR\bposition\x12\x1f\n" +
	"\venqueue_seq\x18\x03 \x01(\x04R\n" +
	"enqueueSeq\"E\n" +
	"\bObserver\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x04R\treplicaId\"$\n" +
	"\x10GetRecordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xd1\x01\n" +
	"\x11GetRecordResponse\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.zuul.v1.RecordR\x06record\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x122\n" +
	"\n" +
	"contenders\x18\x03 \x03(\v2\x12.zuul.v1.ContenderR\n" +
	"contenders\x12/\n" +
	"\tobservers\x18\x04 \x03(\v2\x11.zuul.v1.ObserverR\tobservers\x12\x18\n" +
	"\apartial\x18\x05 \x01(\bR\apartial*R\n" +
	"\bReadMode\x12\x15\n" +
	"\x11READ_MODE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16READ_MODE_LINEARIZABLE\x10\x01\x12\x13\n" +
	"\x0fREAD_MODE_STALE\x10\x02*U\n" +
	"\n" +
	"RecordKind\x12\x17\n" +
	"\x13RECORD_KIND_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10RECORD_KIND_LOCK\x10\x01\x12\x18\n" +
	"\x14RECORD_KIND_ELECTION\x10\x022Q\n" +
	"\aSession\x12F\n" +
	"\tKeepAlive\x12\x19.zuul.v1.KeepAliveRequest\x1a\x1a.zuul.v1.KeepAliveResponse(\x010\x012\xf1\x01\n" +
	"\x06Locker\x123\n" +
	"\x04Lock\x12\x14.zuul.v1.LockRequest\x1a\x15.zuul.v1.LockResponse\x12<\n" +
	"\aTryLock\x12\x17.zuul.v1.TryLockRequest\x1a\x18.zuul.v1.TryLockResponse\x129\n" +
	"\x06Unlock\x12\x16.zuul.v1.UnlockRequest\x1a\x17.zuul.v1.UnlockResponse\x129\n" +
	"\x06Status\x12\x16.zuul.v1.StatusRequest\x1a\x17.zuul.v1.StatusResponse2\xbe\x02\n" +
	"\bElection\x12?\n" +
	"\bCampaign\x12\x18.zuul.v1.CampaignRequest\x1a\x19.zuul.v1.CampaignResponse\x12?\n" +
	"\bProclaim\x12\x18.zuul.v1.ProclaimRequest\x1a\x19.zuul.v1.ProclaimResponse\x129\n" +
	"\x06Leader\x12\x16.zuul.v1.LeaderRequest\x1a\x17.zuul.v1.LeaderResponse\x12:\n" +
	"\aObserve\x12\x17.zuul.v1.ObserveRequest\x1a\x14.zuul.v1.LeaderEvent0\x01\x129\n" +
	"\x06Resign\x12\x16.zuul.v1.ResignRequest\x1a\x17.zuul.v1.ResignResponse2\xc2\x02\n" +
	"\aCluster\x12<\n" +
	"\aMembers\x12\x17.zuul.v1.MembersRequest\x1a\x18.zuul.v1.MembersResponse\x12<\n" +
	"\aAddNode\x12\x17.zuul.v1.AddNodeRequest\x1a\x18.zuul.v1.AddNodeResponse\x12E\n" +
	"\n" +
	"RemoveNode\x12\x1a.zuul.v1.RemoveNodeRequest\x1a\x1b.zuul.v1.RemoveNodeResponse\x129\n" +
	"\x06Shards\x12\x16.zuul.v1.ShardsRequest\x1a\x17.zuul.v1.ShardsResponse\x129\n" +
	"\x06Health\x12\x16.zuul.v1.HealthRequest\x1a\x17.zuul.v1.HealthResponse2\x96\x01\n" +
	"\x06Browse\x12H\n" +
	"\vListRecords\x12\x1b.zuul.v1.ListRecordsRequest\x1a\x1c.zuul.v1.ListRecordsResponse\x12B\n" +
	"\tGetRecord\x12\x19.zuul.v1.GetRecordRequest\x1a\x1a.zuul.v1.GetRecordResponseB2Z0github.com/johnsiilver/zuul/proto/zuul/v1;zuulv1b\x06proto3"

var (
	file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescOnce sync.Once
	file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescData []byte
)

func file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescGZIP() []byte {
	file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescOnce.Do(func() {
		file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDesc), len(file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDesc)))
	})
	return file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDescData
}

var file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_goTypes = []any{
	(ReadMode)(0),               // 0: zuul.v1.ReadMode
	(RecordKind)(0),             // 1: zuul.v1.RecordKind
	(*KeepAliveRequest)(nil),    // 2: zuul.v1.KeepAliveRequest
	(*KeepAliveResponse)(nil),   // 3: zuul.v1.KeepAliveResponse
	(*LockRequest)(nil),         // 4: zuul.v1.LockRequest
	(*LockResponse)(nil),        // 5: zuul.v1.LockResponse
	(*TryLockRequest)(nil),      // 6: zuul.v1.TryLockRequest
	(*TryLockResponse)(nil),     // 7: zuul.v1.TryLockResponse
	(*UnlockRequest)(nil),       // 8: zuul.v1.UnlockRequest
	(*UnlockResponse)(nil),      // 9: zuul.v1.UnlockResponse
	(*StatusRequest)(nil),       // 10: zuul.v1.StatusRequest
	(*StatusResponse)(nil),      // 11: zuul.v1.StatusResponse
	(*CampaignRequest)(nil),     // 12: zuul.v1.CampaignRequest
	(*CampaignResponse)(nil),    // 13: zuul.v1.CampaignResponse
	(*ProclaimRequest)(nil),     // 14: zuul.v1.ProclaimRequest
	(*ProclaimResponse)(nil),    // 15: zuul.v1.ProclaimResponse
	(*LeaderRequest)(nil),       // 16: zuul.v1.LeaderRequest
	(*LeaderResponse)(nil),      // 17: zuul.v1.LeaderResponse
	(*ObserveRequest)(nil),      // 18: zuul.v1.ObserveRequest
	(*LeaderEvent)(nil),         // 19: zuul.v1.LeaderEvent
	(*ResignRequest)(nil),       // 20: zuul.v1.ResignRequest
	(*ResignResponse)(nil),      // 21: zuul.v1.ResignResponse
	(*Endpoint)(nil),            // 22: zuul.v1.Endpoint
	(*Member)(nil),              // 23: zuul.v1.Member
	(*MembersRequest)(nil),      // 24: zuul.v1.MembersRequest
	(*MembersResponse)(nil),     // 25: zuul.v1.MembersResponse
	(*AddNodeRequest)(nil),      // 26: zuul.v1.AddNodeRequest
	(*AddNodeResponse)(nil),     // 27: zuul.v1.AddNodeResponse
	(*RemoveNodeRequest)(nil),   // 28: zuul.v1.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),  // 29: zuul.v1.RemoveNodeResponse
	(*ShardsRequest)(nil),       // 30: zuul.v1.ShardsRequest
	(*ShardsResponse)(nil),      // 31: zuul.v1.ShardsResponse
	(*ShardInfo)(nil),           // 32: zuul.v1.ShardInfo
	(*HealthRequest)(nil),       // 33: zuul.v1.HealthRequest
	(*HealthResponse)(nil),      // 34: zuul.v1.HealthResponse
	(*Record)(nil),              // 35: zuul.v1.Record
	(*ListRecordsRequest)(nil),  // 36: zuul.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil), // 37: zuul.v1.ListRecordsResponse
	(*Contender)(nil),           // 38: zuul.v1.Contender
	(*Observer)(nil),            // 39: zuul.v1.Observer
	(*GetRecordRequest)(nil),    // 40: zuul.v1.GetRecordRequest
	(*GetRecordResponse)(nil),   // 41: zuul.v1.GetRecordResponse
	(*anypb.Any)(nil),           // 42: google.protobuf.Any
}
var file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_depIdxs = []int32{
	0,  // 0: zuul.v1.StatusRequest.read_mode:type_name -> zuul.v1.ReadMode
	0,  // 1: zuul.v1.LeaderRequest.read_mode:type_name -> zuul.v1.ReadMode
	42, // 2: zuul.v1.Endpoint.metadata:type_name -> google.protobuf.Any
	23, // 3: zuul.v1.MembersResponse.members:type_name -> zuul.v1.Member
	32, // 4: zuul.v1.ShardsResponse.shards:type_name -> zuul.v1.ShardInfo
	1,  // 5: zuul.v1.Record.kind:type_name -> zuul.v1.RecordKind
	35, // 6: zuul.v1.ListRecordsResponse.records:type_name -> zuul.v1.Record
	35, // 7: zuul.v1.GetRecordResponse.record:type_name -> zuul.v1.Record
	38, // 8: zuul.v1.GetRecordResponse.contenders:type_name -> zuul.v1.Contender
	39, // 9: zuul.v1.GetRecordResponse.observers:type_name -> zuul.v1.Observer
	2,  // 10: zuul.v1.Session.KeepAlive:input_type -> zuul.v1.KeepAliveRequest
	4,  // 11: zuul.v1.Locker.Lock:input_type -> zuul.v1.LockRequest
	6,  // 12: zuul.v1.Locker.TryLock:input_type -> zuul.v1.TryLockRequest
	8,  // 13: zuul.v1.Locker.Unlock:input_type -> zuul.v1.UnlockRequest
	10, // 14: zuul.v1.Locker.Status:input_type -> zuul.v1.StatusRequest
	12, // 15: zuul.v1.Election.Campaign:input_type -> zuul.v1.CampaignRequest
	14, // 16: zuul.v1.Election.Proclaim:input_type -> zuul.v1.ProclaimRequest
	16, // 17: zuul.v1.Election.Leader:input_type -> zuul.v1.LeaderRequest
	18, // 18: zuul.v1.Election.Observe:input_type -> zuul.v1.ObserveRequest
	20, // 19: zuul.v1.Election.Resign:input_type -> zuul.v1.ResignRequest
	24, // 20: zuul.v1.Cluster.Members:input_type -> zuul.v1.MembersRequest
	26, // 21: zuul.v1.Cluster.AddNode:input_type -> zuul.v1.AddNodeRequest
	28, // 22: zuul.v1.Cluster.RemoveNode:input_type -> zuul.v1.RemoveNodeRequest
	30, // 23: zuul.v1.Cluster.Shards:input_type -> zuul.v1.ShardsRequest
	33, // 24: zuul.v1.Cluster.Health:input_type -> zuul.v1.HealthRequest
	36, // 25: zuul.v1.Browse.ListRecords:input_type -> zuul.v1.ListRecordsRequest
	40, // 26: zuul.v1.Browse.GetRecord:input_type -> zuul.v1.GetRecordRequest
	3,  // 27: zuul.v1.Session.KeepAlive:output_type -> zuul.v1.KeepAliveResponse
	5,  // 28: zuul.v1.Locker.Lock:output_type -> zuul.v1.LockResponse
	7,  // 29: zuul.v1.Locker.TryLock:output_type -> zuul.v1.TryLockResponse
	9,  // 30: zuul.v1.Locker.Unlock:output_type -> zuul.v1.UnlockResponse
	11, // 31: zuul.v1.Locker.Status:output_type -> zuul.v1.StatusResponse
	13, // 32: zuul.v1.Election.Campaign:output_type -> zuul.v1.CampaignResponse
	15, // 33: zuul.v1.Election.Proclaim:output_type -> zuul.v1.ProclaimResponse
	17, // 34: zuul.v1.Election.Leader:output_type -> zuul.v1.LeaderResponse
	19, // 35: zuul.v1.Election.Observe:output_type -> zuul.v1.LeaderEvent
	21, // 36: zuul.v1.Election.Resign:output_type -> zuul.v1.ResignResponse
	25, // 37: zuul.v1.Cluster.Members:output_type -> zuul.v1.MembersResponse
	27, // 38: zuul.v1.Cluster.AddNode:output_type -> zuul.v1.AddNodeResponse
	29, // 39: zuul.v1.Cluster.RemoveNode:output_type -> zuul.v1.RemoveNodeResponse
	31, // 40: zuul.v1.Cluster.Shards:output_type -> zuul.v1.ShardsResponse
	34, // 41: zuul.v1.Cluster.Health:output_type -> zuul.v1.HealthResponse
	37, // 42: zuul.v1.Browse.ListRecords:output_type -> zuul.v1.ListRecordsResponse
	41, // 43: zuul.v1.Browse.GetRecord:output_type -> zuul.v1.GetRecordResponse
	27, // [27:44] is the sub-list for method output_type
	10, // [10:27] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_init() }
func file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_init() {
	if File_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDesc), len(file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_goTypes,
		DependencyIndexes: file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_depIdxs,
		EnumInfos:         file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_enumTypes,
		MessageInfos:      file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_msgTypes,
	}.Build()
	File_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto = out.File
	file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_goTypes = nil
	file_github_com_johnsiilver_zuul_proto_zuul_v1_zuul_proto_depIdxs = nil
}
